create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  rating text not null check (rating in ('good', 'bad')),
  source text,
  created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;

create policy "Allow anonymous feedback inserts"
on public.feedback for insert
to anon
with check (true);
